### ISSUE TITLE
Header quebra em resoluções grandes

### ISSUE THREAD

**Issue by victorperin** [guiluchesi/projeto-tive-fome#1]
# Ambiente
- **Navegador**: Chrome ( Versão 54.0.2840.100 (64-bit) )
- **OS**: Ubuntu Mate 16.10
- **Resolução da tela**: 1920x1080 px

# Print
![image](https://cloud.githubusercontent.com/assets/5847145/20654538/8757c0e4-b501-11e6-8c68-716eb9600b10.png)

**Comment by luchesigui** [comment]
Corrigido. Valeu :)
